## P(wine=white|varx)
## P(wine=white)≥0.5 --> white
## P(wine=white)<0.4 --> red

In [8]:
# Importing the neccesary libraries we are going to need
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import seaborn as sns
sns.set(style="white")
sns.set(style="whitegrid", color_codes=True)

In [9]:
!pip install sklearn

In [35]:
df = pd.read_csv("winequality.csv")
df.head(4500)

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4              0.70         0.00             1.9      0.076   
1               7.8              0.88         0.00             2.6      0.098   
2               7.8              0.76         0.04             2.3      0.092   
3              11.2              0.28         0.56             1.9      0.075   
4               7.4              0.70         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
4495            7.0              0.31         0.39             7.5      0.055   
4496            6.7              0.42         0.46             9.7      0.054   
4497            8.6              0.18         0.28             0.8      0.032   
4498            6.2              0.21         0.26            13.1      0.050   
4499            6.1              0.16         0.37             1.1      0.031   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
4495                 42.0                 218.0  0.99652  3.37       0.54   
4496                 67.0                 234.0  0.99848  3.23       0.50   
4497                 25.0                  78.0  0.99104  2.99       0.38   
4498                 59.0                 150.0  0.99772  3.31       0.46   
4499                 37.0                  97.0  0.99220  3.40       0.58   

      alcohol  quality  Type  
0         9.4        5     0  
1         9.8        5     0  
2         9.8        5     0  
3         9.8        6     0  
4         9.4        5     0  
...       ...      ...   ...  
4495     10.3        5     1  
4496      9.0        5     1  
4497     11.1        5     1  
4498      9.0        5     1  
4499     10.5        6     1  

[4500 rows x 13 columns]

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6497 entries, 0 to 6496
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         6497 non-null   float64
 1   volatile acidity      6497 non-null   float64
 2   citric acid           6497 non-null   float64
 3   residual sugar        6497 non-null   float64
 4   chlorides             6497 non-null   float64
 5   free sulfur dioxide   6497 non-null   float64
 6   total sulfur dioxide  6497 non-null   float64
 7   density               6497 non-null   float64
 8   pH                    6497 non-null   float64
 9   sulphates             6497 non-null   float64
 10  alcohol               6497 non-null   float64
 11  quality               6497 non-null   int64  
 12  Type                  6497 non-null   int64  
dtypes: float64(11), int64(2)
memory usage: 660.0 KB


In [12]:
df.dtypes

fixed acidity           float64
volatile acidity        float64
citric acid             float64
residual sugar          float64
chlorides               float64
free sulfur dioxide     float64
total sulfur dioxide    float64
density                 float64
pH                      float64
sulphates               float64
alcohol                 float64
quality                   int64
Type                      int64
dtype: object

In [13]:
df.Type.value_counts()

1    4898
0    1599
Name: Type, dtype: int64

In [14]:
df.groupby('Type').mean()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
Type                                                                            
0          8.319637          0.527821     0.270976        2.538806   0.087467   
1          6.854788          0.278241     0.334192        6.391415   0.045772   

      free sulfur dioxide  total sulfur dioxide   density        pH  \
Type                                                                  
0               15.874922             46.467792  0.996747  3.311113   
1               35.308085            138.360657  0.994027  3.188267   

      sulphates    alcohol   quality  
Type                                  
0      0.658149  10.422983  5.636023  
1      0.489847  10.514267  5.877909

In [15]:
df["Type"] = df["Type"].astype('category')
df.dtypes

fixed acidity            float64
volatile acidity         float64
citric acid              float64
residual sugar           float64
chlorides                float64
free sulfur dioxide      float64
total sulfur dioxide     float64
density                  float64
pH                       float64
sulphates                float64
alcohol                  float64
quality                    int64
Type                    category
dtype: object

In [20]:
x = df[['density']]
y = df['Type']

In [21]:
scaler = StandardScaler()
scaler.fit(x)
scaled_x = scaler.transform(x)

In [22]:
#Splitting our data into train and test dataset
x_train, x_test, y_train, y_test = train_test_split(scaled_x, y , test_size = 0.2, random_state  = 42)

In [23]:
reg = LogisticRegression() #select the algorithm
reg.fit(x_train,y_train) # we fit the algorithm with the training data and the training output

LogisticRegression()

In [28]:
y_hat = reg.predict(x_test) # y_hat holding the prediction made with the algorithm using x_test


In [29]:
acc = metrics.accuracy_score(y_hat,y_test)# To know the accuracy
acc

0.7284615384615385

In [30]:
reg.intercept_ # Intercept of the regression

array([1.4083958])

In [31]:
reg.coef_ # coefficients of the variables / features 

array([[-1.10546687]])

In [32]:
result = pd.DataFrame(data = x.columns, columns = ['Features'])
result['weight'] = np.transpose(reg.coef_)
result['odds'] = np.exp(np.transpose(reg.coef_))
result

Features    weight      odds
0  density -1.105467  0.331056

### Remember we standardized all independents variables so the odds values have no direct interpretation¶
### Nevertheless using citric acid as an example we can say for one standard deviation increase in citric acid it is twice more likely to cause a change in our target variables

In [33]:
cm = confusion_matrix(y_hat,y_test)
cm

array([[ 63,  75],
       [278, 884]], dtype=int64)

In [34]:
# easier to read
cm_df = pd.DataFrame(cm)
cm_df.columns = ['Predicted 0','Predicted 1']
cm_df = cm_df.rename(index={0: 'Actual 0',1:'Actual 1'})
cm_df

Predicted 0  Predicted 1
Actual 0           63           75
Actual 1          278          884